# _data/visiting.yaml
html: |
    <ul>
        <li>Session Co-Chair at the Asilomar Conference on Signals, Systems, and Computers 2024</li>
        <li>Program Committee Member of AAAI 2025</li>
        <li>Reviewer of AISTATS (2022-2026), NeurIPS (2023 – 2025), ICLR (2024–2026), ICML (2024-2025)</li>
        <li>Reviewer of IEEE Transactions on Signal Processing, IEEE Transactions on Networking</li>
    </ul>